### ISSUE TITLE
Uncaught ReferenceError: config is not defined

### ISSUE THREAD

**Issue by swordsreversed** [mageplaza/magento-2-banner-slider#1]
```
at requirejs-config.js:654
at requirejs-config.js:655
at requirejs-config.js:669
```

It seems to be because this file is commented out:

Magento-2-Banner-Slider-extension/view/frontend/requirejs-config.js

Why is it commented out?

**Comment by swordsreversed** [comment]
I uncommented this file and it works now, might need to change this if you are attempting to use the slider.

**Comment by imsamthomas** [comment]
Hi,

Make sure your store is loading only ONE OW Carousel.

Regards,
Sam

**Comment by swordsreversed** [comment]
Ok i did have another carousel loading, i took it out. I went back and commented out the file, cleaned cache (i'm in developer mode) and same error.

**Comment by imsamthomas** [comment]
It may conflict with an other OwlCarousel2, try to disable it to test

**Comment by swordsreversed** [comment]
Thanks all good now.
