### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by swordsreversed** [mageplaza/magento-2-banner-slider#2]
What does config do? I tried putting in an object of owl carousel options:

```
{
    navigation: false,
    items: 1,
    loop: true,
    autoHeight: false,
}
```

but it did not update the options.

**Comment by imsamthomas** [comment]
It is using `owl carousel` configuration. You can use OWL options as user guide

**Comment by imsamthomas** [comment]
Examples: http://owlcarousel2.github.io/OwlCarousel2/demos/demos.html
See User guide: http://owlcarousel2.github.io/OwlCarousel2/docs/started-welcome.html
