### ISSUE TITLE
Invalid Block Type: Mageplaza \BannerSlider\Block\Widget::class does not exist

### ISSUE THREAD

**Issue by birdman002** [mageplaza/magento-2-banner-slider#24]
Installed Via Composer

Trying to add my banner on a custom module using the following code per the documentation 

Another way to add slider to your page
Template .phtml
<php

echo $block-getLayout()->createBlock('Mageplaza\BannerSlider\Block\Widget::class')->setSliderID(1)->toHtml();

>
(I know I missing ? for the php tags the editor wont let me add those)
Is this all I have to do is add the code to my phtml file or do I have to add anything else?
Permissions Issue?

I am running Apache, and Magento 2.2.6 CE

**Comment by wdsdev** [comment]
try this:
echo $block-getLayout()->createBlock('Mageplaza\BannerSlider\Block\Widget')->setSliderID(1)->toHtml();

**Comment by golaod** [comment]
@birdman002 next time when you use `::class`, don't wrap it with apostrophes, so it should be:
```echo $block-getLayout()->createBlock(\Mageplaza\BannerSlider\Block\Widget::class)->setSliderID(1)->toHtml();```

**Comment by medmek** [comment]
Hello,

Mageplaza\BannerSlider\Block\Widget needs to implement Magento\Widget\Block\BlockInterface
PR: [https://github.com/mageplaza/magento-2-banner-slider/pull/45](https://github.com/mageplaza/magento-2-banner-slider/pull/45)

**Comment by DrakeJack** [comment]
Thanks for the solution, I've merge to the Master branch, you should download or reinstall to get the update.

**Comment by ankitsrivastava777** [comment]
not working still giving the same error.
