### ISSUE TITLE
White screen of death when creating/adding sliders to homepage. Magento 2.3.3

### ISSUE THREAD

**Issue by extremeskillz** [mageplaza/magento-2-banner-slider#42]
OS: Ubuntu 1604LTS Server
Web Server: Apache2.3
PHP: 7.2
Magento 2.3.3 CE

Hello all,
I'm running into an issue where I create banners and sliders and causing Magento to panic. This results in getting a white screen of death. As soon as I delete all banners and sliders the site is restored. I tried looking at the logs but they are clean. To me this tells me I'm doing something right as far as creating the content but for some reason its is not working as it should. 

If you need more info please let me know.

**Comment by Iamwade** [comment]
ran into the same problem. Magento 2.3.2
![image](https://user-images.githubusercontent.com/33068778/69233382-79388000-0b95-11ea-9cd1-bbda472fd2a6.png)

**Comment by johnekj** [comment]
It happens when slider is not assigned to at least one page element. Than execution breaks in this line:
https://github.com/mageplaza/magento-2-banner-slider/blob/286b46f1873b2ba365ab473bfefede6d620b1604/Observer/AddBlock.php#L90

So it is impossible to use a slider only using widgets. It must be assigned to some page element in slider configuration.

**Comment by bdtrung** [comment]
> It happens when slider is not assigned to at least one page element. Than execution breaks in this line:
> https://github.com/mageplaza/magento-2-banner-slider/blob/286b46f1873b2ba365ab473bfefede6d620b1604/Observer/AddBlock.php#L90
> 
> So it is impossible to use a slider only using widgets. It must be assigned to some page element in slider configuration.

Thank you for contributing the patch to fix the issue.
We will review and going to merge into the master branch.
Hope you will have more contribute to improving our extension to be better.
