### ISSUE TITLE
Missing div in banner form field (sliders)

### ISSUE THREAD

**Issue by medmek** [mageplaza/magento-2-banner-slider#47]
Hello,

I've noticed that when trying to add other fields to banner edit form after Sliders field, it adds them inside its outer div .admin__field, so i find that there's a missing closing div tag in 
https://github.com/mageplaza/magento-2-banner-slider/blob/55b848a9799c7a710e6ac493d3e46135f06443b8/Block/Adminhtml/Banner/Edit/Tab/Render/Slider.php#L78-L88

Thank's

**Comment by bdtrung** [comment]
Thank you for contributing the patch to fix the issue.
We will review and going to merge into the master branch.
Hope you will have more contribute to improving our extension to be better.
