### ISSUE TITLE
Slider and Banner cache invalidation 

### ISSUE THREAD

**Issue by medmek** [mageplaza/magento-2-banner-slider#49]
Hello,

I noticed some slider/banner weren't showing changes right away after save (had to flush cache manually)

Models needs to implement IdentityInterface in order to get the native cache invalidation (`$_cacheTag` and `function getIdentities()` are well implemented already but see `vendor/magento/framework/App/Cache/Tag/Strategy/Identifier.php:24`)

`Block/Slider.php` : 
Views that display that content needs, according to doc, to implement the IdentityInterface
[Dev Docs #invalidate-public-content](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/cache/page-caching/public-content.html#invalidate-public-content)

**Comment by bdtrung** [comment]
Thank you for contributing the patch to fix the issue.
We will review and going to merge into the master branch.
Hope you will have more contribute to improving our extension to be better.
