### ISSUE TITLE
Something went wrong while saving the Slider.

### ISSUE THREAD

**Issue by dumbly91** [mageplaza/magento-2-banner-slider#51]
When I want to save a Slider I got only this error and I don't know how can I get more info about the error. I have Magento 2.3 , With the banners I have no problem
![image](https://user-images.githubusercontent.com/9941787/69905389-5e75c080-1378-11ea-9cdc-cf36830996e8.png)

Thanks!

**Comment by padhu1980** [comment]
I am also having this error....

**Comment by toandt98** [comment]
Hello, I am Uri from Mageplaza Support Team. Please let me assist you on this issue.
I fixed it by changing the Media.php file of the core module
( Path: Core/Helper/Media.php) with the following file:

https://drive.google.com/file/d/1vGerJEZe9nt7DIgnVOUxsOa0igb-vCld/view?usp=sharing

If it does not work, please contact us again.

**Comment by padhu1980** [comment]
Still having the same......
Something went wrong while saving the Slider. :(

**Comment by padhu1980** [comment]
This solution fixed the problem.  https://github.com/mageplaza/magento-2-product-slider/issues/69

changed the line https://github.com/mageplaza/module-core/blob/master/Helper/AbstractData.php#L37

use Zend_Serializer_Adapter_PhpSerialize;

with:

use Magento\Framework\Serialize\Serializer\Serialize;

and line https://github.com/mageplaza/module-core/blob/master/Helper/AbstractData.php#L331

return $this->objectManager->get(Zend_Serializer_Adapter_PhpSerialize::class);

with:

return $this->objectManager->get(Serialize::class);

**Comment by toandt98** [comment]
Firstly very sorry for not being able to answer you immediately.

Thank you for the solution you share, **padhu1980**.
That solution is exactly right and glad you have solved the problem.

Did you solve this problem? **dumbly91**
If possible, use the solution above of **padhu1980**, If it works for you please let us know.

Thanks a lot!

**Comment by toandt98** [comment]
Close due to no response within 7 days.

**Comment by mandeepsng** [comment]
Get this error when create new banner.
![New-Banner-Banner-Sparsh-Banners-Magento-Admin](https://user-images.githubusercontent.com/80085652/121312716-4692db80-c923-11eb-9ac5-22c69f816449.png)

currenlty install magento 2.4.1.
php version = 7.4
Please help
