### ISSUE TITLE
Position can not saved if we deselect all position 

### ISSUE THREAD

**Issue by jigar48** [mageplaza/magento-2-banner-slider#54]
Hello,

When you select position and saved it, after again you deselect all position and then save it, It does not save it. It still selected position.
https://prnt.sc/r4y37l

**Comment by toandt98** [comment]
Hello,
I'm Uri from Mageplaza Support Team. Please let me help you on this issue.

Please try it with my custom module:
https://drive.google.com/file/d/1uKm2Z-4ZKmwJ8d_jFls6Unt-QLrGWCnR/view?usp=sharing

In addition, this module I have added a separate option to use the code snippet: https://prnt.sc/r55atf

I hope it will help you fix the problem.
Best Regards.
