### ISSUE TITLE
Error in console (MIME type)

### ISSUE THREAD

**Issue by axelmo-smile** [mageplaza/magento-2-banner-slider#57]
Hi

I have an error in front : "Refused to apply style from 'bannerslider.css' because its MIME type ('text/html') is not a supported stylesheet MIME type and strict MIME checking is enabled."

Can you help me ? 

Thanks

**Comment by Tuvpt** [comment]
You can refer to some tips to solve this problem here. https://stackoverflow.com/questions/48248832/stylesheet-not-loaded-because-of-mime-type
