### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'banners' in 'order clause', query was: SELECT `main_table`.* FROM `mageplaza_bannerslider_slider` AS `main_table` ORDER BY banners ASC  LIMIT 20

### ISSUE THREAD

**Issue by tarunm60** [mageplaza/magento-2-banner-slider#58]
When I am going to select filter "Number of banner" from Manage Sliders I got below error:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'banners' in 'order clause', query was: SELECT `main_table`.* FROM `mageplaza_bannerslider_slider` AS `main_table` ORDER BY banners ASC  LIMIT 20`

**Comment by Tuvpt** [comment]
We are very sorry for this issue. In the manager sliders, you cannot filter or sort by Number of banner.
We will fix it in the next updated version
