### ISSUE TITLE
How to configure the slider on the home page as fullwidith?

### ISSUE THREAD

**Issue by felipe-aranha** [mageplaza/magento-2-banner-slider#60]
I'm trying to set up a slider on the home page as fullwidth but I can't. When the "Top of Page" option is activated, it is positioned before the menu.

**Comment by Tuvpt** [comment]
please edit file \app\code\Mageplaza\BannerSlider\Observer\AddBlock.php like screenshot
![image](https://user-images.githubusercontent.com/32826247/77717185-62f27300-7012-11ea-93ef-f0ad83ddb7ad.png)

**Comment by felipe-aranha** [comment]
thank you.
