### ISSUE TITLE
Slider save action automatically sets from date in the future

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-banner-slider#61]
Magento 2.3.4
PHP 7.2

1. Create a slider
2. Leave from_date empty
3. Save
-> from_date will automatically be set to today
4. Open same slider again
5. Save again without any changes
->from_date gets automatically set to some future date

In my case the date was initially set to april, 15th 2020 ("2020-04-15" in the database). After saving again the new date is march, 4th 2021 (database: "2021-03-04").

**Comment by OvalMedia** [comment]
Must be related to my locale setting (german). Once I switch to english the problem diappears.

**Comment by OvalMedia** [comment]
Zend_Filter_Input is messing with the date format. Uncommenting this in _filterData function also eliminates the problem.

**Comment by toandt98** [comment]
Good week, OvalMedia

First of all, thank you for contacting us. I'm Uri from Mageplaza Support Team. 

It is great that you have resolved the issue quickly and provided us with suggestions.
We appreciate your support, I will send this issue to the upgrade department for review and inclusion in the next upgrade.

Thank you again! Stay Safe, Stay Healthy, and Stay Happy!
Best Regards,
​Uri
