### ISSUE TITLE
Cannot deselect Slider Location / Position

### ISSUE THREAD

**Issue by AlexQx** [mageplaza/magento-2-banner-slider#63]
After selecting a Slider Location and saving the slider, I cannot revert the slider to having no position selected. Deselecting with ctrl+click and saving it reverts to the latest saved position.

Using the latest dev-master bcc800c

edit: Magento version 2.3.4

**Comment by toandt98** [comment]
First of all, thank you for contacting us.
I'm Uri from Mageplaza Support Team. Please let me assist you on this issue.

This is a problem in our old version, Please try with my new upgrade version, you can download it here (It has not been released yet):

- https://drive.google.com/file/d/1deGWAmg4fdUrlfkPSYxp7yGbeEFFQnC4/view?usp=sharing

Note: When using the snippet code, please select position as: Using snippet code, widget 
It will help you solve this problem.

Best Regards,
Uri

**Comment by AlexQx** [comment]
Thank you for the quick reply. The custom position option works great. Will this be updated in composer soon?
