### ISSUE TITLE
Not registered handle mpbannerslider_banner_listing_data_source

### ISSUE THREAD

**Issue by eBusinessAtlantique** [mageplaza/magento-2-banner-slider#67]
Hello,
I have this error "Not registered handle mpbannerslider_banner_listing_data_source" when I go to Manage Banners.
and "Not registered handle mpbannerslider_slider_listing_data_source" when I go to Manage Sliders.
I use M2.3.4-p2.
Thanks for the help you can provide me.
Maxime

**Comment by Uri-Mageplaza** [comment]
Hello @eBusinessAtlantique 

In this regard, you may have an error during the installation process. 
Please try uninstalling and reinstalling the module.

Thanks you!
