### ISSUE TITLE
Date range issue

### ISSUE THREAD

**Issue by cesarphinx** [mageplaza/magento-2-banner-slider#71]
There is a problem in the administrator when creating or editing a slider with a range of dates, I attach screenshots.
The version of mageplaza/module-banner-slider is 2.0.5 and the version of mageplaza/module-core is 1.4.8 and the version of magento is 2.3.5

**Case 1:** Selecting "Display from" November 1, 2020 and "Display to" November 30, 2020 saves an incorrect "from" date
![Captura de Pantalla 2020-10-20 a la(s) 16 13 41](https://user-images.githubusercontent.com/73196221/96635311-1514c380-12f2-11eb-89af-d20868e906f3.png)
![Captura de Pantalla 2020-10-20 a la(s) 16 14 23](https://user-images.githubusercontent.com/73196221/96635358-22ca4900-12f2-11eb-865e-26139db9d4dd.png)

**Cese 2:** When selecting "Display from" October 20, 2020 and "Display to" October 31, 2020, I get the error: "'End Date must follow Start Date.'" and an incorrect date appears in the "Display from" field of the form
![Captura de Pantalla 2020-10-20 a la(s) 16 12 01](https://user-images.githubusercontent.com/73196221/96635465-42fa0800-12f2-11eb-9d0e-58e30c6b67b6.png)
![Captura de Pantalla 2020-10-20 a la(s) 16 12 35](https://user-images.githubusercontent.com/73196221/96635485-4a211600-12f2-11eb-9f17-2404389b0dc4.png)
![Captura de Pantalla 2020-10-20 a la(s) 16 13 03](https://user-images.githubusercontent.com/73196221/96635515-5311e780-12f2-11eb-8273-de24d3b93842.png)

**Comment by Uri-Mageplaza** [comment]
Hello,
In this issue, we have fixed it here: 95b5e5f59e6b06aed0a0420a7f45f71d0451b355
We'll be releasing a fix soon.

Have a nice day!
