### ISSUE TITLE
Minor bug in setup script

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-banner-slider#73]
The install schema has a typo (w/o consequences though):

`->addColumn('name', Table::TYPE_TEXT, 255, ['nullable => false'], 'Banner Name')`
probably should be
`->addColumn('name', Table::TYPE_TEXT, 255, ['nullable' => false], 'Banner Name')`

**Comment by Tuvpt** [comment]
Thanks for your comments. We will add it to an upcoming update. 98e5064f8058a15ebfbac1ccfc3320f7faade1ae
