### ISSUE TITLE
Undefined index exception

### ISSUE THREAD

**Issue by vertic4l** [mageplaza/magento-2-banner-slider#81]
Just wanted to try it out but ended up with:

`main.CRITICAL: Notice: Undefined index: id in app/code/Magento/Config/Model/Config/Structure/Element/Iterator.php on line 63 `

what's the problem here?

just installed with:

composer require mageplaza/module-banner-slider   
php bin/magento setup:upgrade

Magento 2.4.2

**Comment by giaphn** [comment]
Hi, 
I'm Shox from Mageplaza. Please install the Mageplaza_Core module.
it is a required module for other mageplaza extensions to work

**Comment by giaphn** [comment]
Closed due no response within 7 days.
