### ISSUE TITLE
Compatibility with aws s3

### ISSUE THREAD

**Issue by HenriqueRBarbosa** [mageplaza/magento-2-banner-slider#82]
I'm not able to consume the images stored in aws s3, is there this configuration in the module. I'm using magento version 2.4.2 which has aws s3 natively.

Example: the image saved right in the mageplaza folder in aws, but it doesn't display it, it displays broken link.

**Comment by fabiano-mallmann** [comment]
Please, give me more details

**Comment by giaphn** [comment]
Currently, our extension doesn't support external upload. 
You can try using type advance to upload it.
If impossible, I regret that we cannot help you further in this matter.
I am genuinely thankful for your understanding

**Comment by HenriqueRBarbosa** [comment]
> Currently, our extension doesn't support external upload.
> You can try using type advance to upload it.
> If impossible, I regret that we cannot help you further in this matter.
> I am genuinely thankful for your understanding

**Comment by HenriqueRBarbosa** [comment]
Ok, thanks for the reply.
